# Generated by Django 4.2.1 on 2023-10-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('roundId', models.UUIDField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactionId', models.UUIDField(unique=True)),
                ('currency', models.CharField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
