# Generated by Django 4.2.1 on 2023-10-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0004_bet_clientid_alter_bet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='roundId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bet',
            name='transactionId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refundTransactionId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='refund',
            name='roundId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='refund',
            name='transactionId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='win',
            name='roundId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='win',
            name='transactionId',
            field=models.CharField(max_length=255),
        ),
    ]
